---
- hosts: arbeitsplatz
  become: true

  pre_tasks:
    - name: Setting hostname
      hostname:
        name: '{{ inventory_hostname }}'
        use: systemd

    - name: changing hostname in /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: "127.0.1.1 newmachine"
        line: '127.0.1.1 {{ inventory_hostname }}.phytec.de'

    - name: restart networkmanager
      tags: config
      systemd:
        name: NetworkManager.service
        state: restarted

  roles:
    - arbeitsplatzsoftware
    - nosnap
    - joinad
    - notes
    - pam_mounts
    - arbeitsplatzconfig
