---
- name: configure dhcp snooping
  hosts: dellos6
  become: true
  gather_facts: no

  tasks:
    - name: enable dhcp snooping
      dellos6_config:
        lines:
          - ip dhcp snooping
          - ip dhcp snooping vlan 1-4093

    - name: enable trusted port-channel ports
      dellos6_config:
        lines:
          - ip dhcp snooping trust
        parents: ['interface range port-channel all']

    - name: enable trusted tengigabit ports
      dellos6_config:
        lines:
          - ip dhcp snooping trust
        parents: ['interface range tengigabitethernet all']
        save: yes

    - name: save new config
      dellos6_command:
        commands:
          - command: write
            prompt: '\(y/n\)\s?$'
            answer: 'y'

