---
- hosts: all
  become: true
  gather_facts: no
  vars_prompt:

    - name: username
      prompt: Enter username
      private: false

  tasks:

    - name: Ensure no_ssh_pw exists
      group:
        name: no_ssh_pw
        state: present

    - name: create User
      user:
        name: '{{ username }}'
        password: ''
        groups: no_ssh_pw, sudo
        append: yes
        shell: /bin/bash

    - name: expire passowrd
      shell: "passwd -e {{ username }}"

