---
- name: configure dhcp snooping
  hosts: dellos6
  become: true
  gather_facts: no

  tasks:
    - name: enable dhcp snooping
      dellos6_config:
        lines:
          - Line 1
          - line 2
