---
- hosts: testfeld
  become: true

  pre_tasks:
    - name: Setting hostname
      hostname:
        name: '{{ inventory_hostname }}'
        use: systemd

    - name: changing hostname in /etc/hosts
      lineinfile:
        path: /etc/hosts
        regexp: "127.0.1.1 newmachine"
        line: '127.0.1.1 {{ inventory_hostname }}.phytec.de'

  roles:
    - icinga
    - testfeldsoftware
    - unattendedautoremove
    - joinad
