- name: Joining AD
  shell: echo '{{ adpass }}' | realm join -U administrator phytec.de

- name: fill /etc/skel
  unarchive:
    src: ../files/skel.tar.gz
    dest: /etc/skel
    owner: root
    group: root

- name: add /etc/skel in pam config
  lineinfile:
    path: /etc/pam.d/common-account
    line: session required pam_mkhomedir.so skel=/etc/skel/ umask=0077
    state: present

- name: update krb5.conf
  copy:
    dest: "/etc/krb5.conf"
    content: |
      [libdefaults]
      udp_preference_limit = 0
      default_realm = PHYTEC.DE
      dns_lookup_realm = true
      dns_lookup_kdc = true
      forwardable = yes
      default_ccache_name = FILE:/tmp/krb5cc_%{euid}

- name: update sssd.conf
  copy:
    dest: "/etc/sssd/sssd.conf"
    content: |
      [sssd]
      domains = phytec.de
      config_file_version = 2
      services = nss, pam
        
      [domain/phytec.de]
      default_shell = /bin/bash
      krb5_store_password_if_offline = True
      cache_credentials = True
      krb5_realm = PHYTEC.DE
      realmd_tags = manages-system joined-with-adcli
      id_provider = ad
      fallback_homedir = /home/%u
      ad_domain = phytec.de
      use_fully_qualified_names = False
      ldap_id_mapping = True
      ldap_schema = ad
      ldap_idmap_range_min = 10000
      ldap_idmap_range_max = 60000
      ldap_idmap_range_size = 50000
      ldap_idmap_autorid_compat = True
      ldap_idmap_default_domain = phytec.de
      access_provider = ad
      ad_gpo_ignore_unreadable = True

- name: stop sssd
  systemd:
    name: sssd
    state: stopped

- name: delete sssd DB
  shell: rm -rf /var/lib/sss/db/*

- name: change permission of sssd.conf
  file:
    path: /etc/sssd/sssd.conf
    mode: '600'

- name: start sssd
  systemd:
    name: sssd
    state: started
