---
- name: create/update 50unattended-upgrades
  copy:
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    content: |
      // Automatically upgrade packages from these (origin, archive) pairs
      Unattended-Upgrade::Allowed-Origins {
          // ${distro_id} and ${distro_codename} will be automatically expanded
          "${distro_id} ${distro_codename}";
          "${distro_id} ${distro_codename}-security";
          "${distro_id} ${distro_codename}-updates";
      //  "${distro_id} ${distro_codename}-proposed-updates";
          "ubuntu icinga-${distro_codename} icinga-${distro_codename}";
      };

      // List of packages to not update
      Unattended-Upgrade::Package-Blacklist {
      //  "vim";
      //  "libc6";
      //  "libc6-dev";
      //  "libc6-i686";
      };

      // Do automatic removal of new unused dependencies after the upgrade
      // (equivalent to apt-get autoremove)
      Unattended-Upgrade::Remove-Unused-Dependencies "true";
    force: true

- name: Update unattended upgrades configuration
  command: dpkg-reconfigure -f noninteractive unattended-upgrades
