---
- name: Give sudo access to domain users
  tags: AD
  blockinfile:
    path: /etc/sudoers
    insertafter: '%sudo ALL=(ALL:ALL) ALL'
    block: |
      %domain\ users  ALL=(ALL:ALL) ALL

      #- name: disable phytec user
      #  tags: config
      #  user:
      #    name: phytec
      #    state: present
      #    password_lock: true
      #    shell: "/sbin/nologin"

