---
- name: Give sudo access to domain users
  tags: AD
  blockinfile:
    path: /etc/sudoers
    insertafter: '%sudo ALL=(ALL:ALL) ALL'
    block: |
      %domain\ users  ALL=(ALL:ALL) ALL

- name: fill /etc/skel
   tags: config
   unarchive:
    src: skel.tar.gz
    dest: /etc/skel
    owner: root
    group: root


- name: disable phytec user
  tags: config
  user:
    name: phytec
    state: present
    password_lock: true
    shell: "/sbin/nologin"

