---
- name: Remove common snaps
  ignore_errors: true
  community.general.snap:
    name:
      - firefox
      - snap-store
      - gnome-3-38-2004
      - gnome-42-2204
      - gtk-common-themes
      - snapd-desktop-integration
    state: absent

- name: Remove lxd
  ignore_errors: true
  community.general.snap:
    name: lxd
    state: absent

- name: remove bare
  ignore_errors: true
  community.general.snap:
    name: bare
    state: absent

- name: Remove core2X
  ignore_errors: true
  community.general.snap:
    name: 
      - core20
      - core22
    state: absent

- name: Remove snapd
  ignore_errors: true
  community.general.snap:
    name: snapd
    state: absent

- name: purge snapd
  apt:
    name: snapd
    purge: yes
    state: absent

- name: Prevent Snap installs
  copy:
    src: nosnap.pref
    dest: /etc/apt/preferences.d/nosnap.pref
    owner: root
    group: root
    mode: 0440
