---
- name: purge snapd
  apt:
    name: snapd
    purge: yes
    state: absent

- name: Prevent Snap installs
  copy:
    src: nosnap.pref
    dest: /etc/apt/preferences.d/nosnap.pref
    owner: root
    group: root
    mode: 0440
