---
- name: install required packages
  apt:
    update_cache: yes
    name:
      - jq
      - curl
    state: present

- name: copy privacyidea-authorizedkeys
  copy:
    src: privacyidea-authorizedkeys
    dest: /opt
    mode: '0755'

- name: change sshd_config
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '{{ item.From }}'
    line: '{{ item.To }}'
    state: present
    validate: "sshd -t -f %s"
  with_items:
      - { From: '^AuthorizedKeysCommandUser ', To: 'AuthorizedKeysCommandUser nobody'}
      - { From: '^AuthorizedKeysCommand ', To: 'AuthorizedKeysCommand /opt/privacyidea-authorizedkeys'}

- name: match group no_ssh_pw
  lineinfile:
    path: /etc/ssh/sshd_config
    insertafter: "^AuthorizedKeysCommand"
    line: "Match group no_ssh_pw"
    firstmatch: yes
    state: present
    validate: "sshd -t -f %s"

- name: disable pw login
  lineinfile:
    path: /etc/ssh/sshd_config
    insertafter: "Match group no_ssh_pw"
    line: "PasswordAuthentication no"
    firstmatch: yes
    state: present
    validate: "sshd -t -f %s"

- name: restart ssh process
  service:
    name: ssh
    state: restarted
