---
- name: restart NetworkManager for preventing errors
  systemd:
    name: NetworkManager
    state: restarted

- name: Add Mozilla repo
  apt_repository:
    repo: ppa:mozillateam/ppa

- name: install firefox
  apt:
    name: firefox
    state: present
    default_release: 'o=LP-PPA-mozillateam'

- name: allow unattended upgrades
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    line: 'Unattended-Upgrade::Allowed-Origins:: "LP-PPA-mozillateam:${distro_codename}";'
    state: present

- name: give Mozilla repo high prio
  copy:
    src: mozilla.pref
    dest: /etc/apt/preferences.d/
    owner: root
    group: root
    mode: 0440
      
- name: uninstall update-manager
  apt:
    name: update-manager
    state: absent
