---
- name: enable DHCP snooping
  hosts: dellos6
  become: true
  gather_facts: no

  tasks:
    - name: enable dhcp snooping
      dellos6_config:
        lines:
          - ip dhcp snooping
          - ip dhcp snooping vlan 1-4093

    - name: enable trusted ports
      dellos6_config:
        lines:
          - ip dhcp snooping trust
        parents: ['interface range port-channel all']
