---
- hosts: ubuntu
  become: true
  tasks:
    - name: set unattended upgrades autoremove
      lineinfile:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        regexp: '^//Unattended-Upgrade::Remove-Unused-Dependencies\s+"false";$'
        line: 'Unattended-Upgrade::Remove-Unused-Dependencies "true";'
        state: present

    - name: Update unattended upgrades configuration
      command: dpkg-reconfigure -f noninteractive unattended-upgrades
